apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    role: webserver
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      role: webserver
      app: apache
  template:
    metadata:
      labels:
        role: webserver
        app: apache
    spec:
      containers:
      - name: frontend
        image: httpd
        ports:
        - containerPort: 80
